name: social_soup
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ms_undraw: ^3.1.0+3
  flutter_dotenv: ^5.0.2
  mongo_dart: ^0.8.1
  fpdart: ^0.3.0
  get: ^4.6.5
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  salomon_bottom_bar: ^3.3.1
  dartx: ^1.1.0
  flutter_svg: ^1.1.6
  intl:
  image_picker: ^0.8.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  freezed: ^2.3.0
  json_serializable: ^6.5.4

flutter:
  assets:
    - .env

  uses-material-design: true
